### ISSUE TITLE
issue_reproducible archive should include logs and outputs

### ISSUE THREAD

**Issue by proppy** [The-OpenROAD-Project/OpenLane#1589]
### Description

Currently the `issue_reproducible` archive only include input and script necessary to reproduce the issue.

### Proposal

It would be nice for it to also include output and logs file so that you have a reference to compare against when trying to reproduce the issue.

**Comment by donn** [comment]
Outputs, by nature, are not included because the reproducibles are created either before a step is run or when it crashes.

I so far have not encountered a situation where the reproducible changed behavior much between environments as the environments are identical (Docker containers) regardless so I think it's moot. The relevant part(s) of the logs are uploaded as part of issue templates so that's not much of a concern either.
