### ISSUE TITLE
html rendering in regression_results/readme

### ISSUE THREAD

**Issue by marwaneltoukhy** [The-OpenROAD-Project/OpenLane#513]
**Describe the bug**
Test results should be rendered as html

**To Reproduce**
1. Go to 'regression_results/'
2. Click on 'sky130_fd_sc_hd'

**Comment by marwaneltoukhy** [comment]
`https://htmlpreview.github.io/?` no longer renders csv files in HTML

**Comment by donn** [comment]
No, I removed that.

I didn't want for there to be data duplication on our gold standard. People can use Excel, I'm sure.

**Comment by donn** [comment]
No, I removed the HTML files in the interest of data de-duplication. htmlpreview does not render CSV files, it merely allows the html files to be rendered instead of being shown as plaintext.

Clearly, I neglected to update the Readme, so thank you for pointing that out. We can probably also utilize some web app that renders the CSV files browser-side.

**Comment by marwaneltoukhy** [comment]
github renders CSV files neatly, maybe we could just redirect to the respective CSV file on github.

**Comment by donn** [comment]
Possible. Would you consider opening a PR?

**Comment by marwaneltoukhy** [comment]
It is added to PR #531 along with timing optimization before global routing
